-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eufolkia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eufolkia` ;

-- -----------------------------------------------------
-- Schema eufolkia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eufolkia` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `eufolkia` ;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_ESTADO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_ESTADO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_MUNICIPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_MUNICIPIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_MUNICIPIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MUNICIPIO` VARCHAR(45) NULL,
  `TBL_ESTADO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_MUNICIPIO_TBL_ESTADO`
    FOREIGN KEY (`TBL_ESTADO_ID`)
    REFERENCES `eufolkia`.`TBL_ESTADO` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_MUNICIPIO_TBL_ESTADO_idx` ON `eufolkia`.`TBL_MUNICIPIO` (`TBL_ESTADO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_COLONIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_COLONIA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_COLONIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COLONIA` VARCHAR(45) NULL,
  `CODIGO_POSTAL` VARCHAR(45) NULL,
  `TBL_MUNICIPIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_COLONIA_TBL_MUNICIPIO1`
    FOREIGN KEY (`TBL_MUNICIPIO_ID`)
    REFERENCES `eufolkia`.`TBL_MUNICIPIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_COLONIA_TBL_MUNICIPIO1_idx` ON `eufolkia`.`TBL_COLONIA` (`TBL_MUNICIPIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_TDOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_TDOMICILIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_TDOMICILIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(45) NULL,
  `RUTA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `APELLIDO_PATERNO` VARCHAR(45) NULL,
  `APELLIDO_MATERNO` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `TELEFONO` VARCHAR(45) NULL,
  `CONTRASENA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_DOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_DOMICILIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_DOMICILIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CALLE` VARCHAR(45) NULL,
  `NUMERO_EXTERIOR` VARCHAR(45) NULL,
  `NUMERO_INTERIOR` VARCHAR(45) NULL,
  `TBL_DOMICILIOcol` VARCHAR(45) NULL,
  `TBL_COLONIA_ID` INT NOT NULL,
  `TBL_TDOMICILIO_ID` INT NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_COLONIA1`
    FOREIGN KEY (`TBL_COLONIA_ID`)
    REFERENCES `eufolkia`.`TBL_COLONIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_TDOMICILIO1`
    FOREIGN KEY (`TBL_TDOMICILIO_ID`)
    REFERENCES `eufolkia`.`TBL_TDOMICILIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `eufolkia`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_COLONIA1_idx` ON `eufolkia`.`TBL_DOMICILIO` (`TBL_COLONIA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_TDOMICILIO1_idx` ON `eufolkia`.`TBL_DOMICILIO` (`TBL_TDOMICILIO_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_USUARIO1_idx` ON `eufolkia`.`TBL_DOMICILIO` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_TNOTIFICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_TNOTIFICACION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_TNOTIFICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(45) NULL,
  `TIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_NOTIFICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_NOTIFICACION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_NOTIFICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NULL,
  `FECHA` VARCHAR(45) NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  `TBL_TNOTIFICACION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_NOTIFICACION_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `eufolkia`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_NOTIFICACION_TBL_TNOTIFICACION1`
    FOREIGN KEY (`TBL_TNOTIFICACION_ID`)
    REFERENCES `eufolkia`.`TBL_TNOTIFICACION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_NOTIFICACION_TBL_USUARIO1_idx` ON `eufolkia`.`TBL_NOTIFICACION` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_NOTIFICACION_TBL_TNOTIFICACION1_idx` ON `eufolkia`.`TBL_NOTIFICACION` (`TBL_TNOTIFICACION_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_ARTISTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_ARTISTA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_ARTISTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BIOGRAFIA` VARCHAR(45) NULL,
  `LOGO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_GENERO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_GENERO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_GENERO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_DISCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_DISCO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_DISCO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `PORTADA` VARCHAR(45) NULL,
  `FECHA` VARCHAR(45) NULL,
  `DURACION` VARCHAR(45) NULL,
  `TBL_ARTISTA_ID` INT NOT NULL,
  `TBL_GENERO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DISCO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `eufolkia`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_GENERO1`
    FOREIGN KEY (`TBL_GENERO_ID`)
    REFERENCES `eufolkia`.`TBL_GENERO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_ARTISTA1_idx` ON `eufolkia`.`TBL_DISCO` (`TBL_ARTISTA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_GENERO1_idx` ON `eufolkia`.`TBL_DISCO` (`TBL_GENERO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_CANCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_CANCION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_CANCION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DURACION` VARCHAR(45) NULL,
  `TBL_DISCO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_CANCION_TBL_DISCO1`
    FOREIGN KEY (`TBL_DISCO_ID`)
    REFERENCES `eufolkia`.`TBL_DISCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_CANCION_TBL_DISCO1_idx` ON `eufolkia`.`TBL_CANCION` (`TBL_DISCO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_VIDEO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_VIDEO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_VIDEO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `ARCHIVO` VARCHAR(45) NULL,
  `DURACION` INT NULL,
  `TBL_ARTISTA_ID` INT NOT NULL,
  `TBL_GENERO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_VIDEO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `eufolkia`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_VIDEO_TBL_GENERO1`
    FOREIGN KEY (`TBL_GENERO_ID`)
    REFERENCES `eufolkia`.`TBL_GENERO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_VIDEO_TBL_ARTISTA1_idx` ON `eufolkia`.`TBL_VIDEO` (`TBL_ARTISTA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_VIDEO_TBL_GENERO1_idx` ON `eufolkia`.`TBL_VIDEO` (`TBL_GENERO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_PRODUCTOSERVICIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_PRODUCTOSERVICIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_PRODUCTOSERVICIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `PRECIO` DOUBLE NULL,
  `CANTIDAD` INT NULL,
  `IMAGEN` VARCHAR(45) NULL,
  `TBL_ARTISTA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_PRODUCTOSERVICIO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `eufolkia`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_PRODUCTOSERVICIO_TBL_ARTISTA1_idx` ON `eufolkia`.`TBL_PRODUCTOSERVICIO` (`TBL_ARTISTA_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eufolkia`.`TBL_DOCUMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eufolkia`.`TBL_DOCUMENTO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eufolkia`.`TBL_DOCUMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  `ARCHIVO` VARCHAR(45) NULL,
  `FECHA` VARCHAR(45) NULL,
  `TBL_ARTISTA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DOCUMENTO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `eufolkia`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOCUMENTO_TBL_ARTISTA1_idx` ON `eufolkia`.`TBL_DOCUMENTO` (`TBL_ARTISTA_ID` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
